In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Saurabh\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | 3          |   3% 
conda-4.14.0         | 937 KB    | #5         |  15% 
conda-4.14.0         | 937 KB    | ###7       |  38% 

Note: you may need to restart the kernel to use updated packages.
conda-4.14.0         | 937 KB    | #####

In [4]:
import numpy as np

In [21]:
lst=[1,2,3,4,5]
array=np.array(lst)

In [4]:
type(array)

numpy.ndarray

In [22]:
array

array([1, 2, 3, 4, 5])

In [23]:
array.shape

(5,)

In [10]:
l1=[1,2,34,5]
l2=[4,8,6,7]
array=np.array([l1,l2])

In [11]:
array

array([[ 1,  2, 34,  5],
       [ 4,  8,  6,  7]])

In [14]:
array.reshape(4,2)

array([[ 1,  2],
       [34,  5],
       [ 4,  8],
       [ 6,  7]])

In [15]:
array.reshape(1,8)

array([[ 1,  2, 34,  5,  4,  8,  6,  7]])

In [18]:
array[1:,5:]

array([], shape=(1, 0), dtype=int32)

In [24]:
array

array([1, 2, 3, 4, 5])

In [26]:
array[4]

5

In [29]:
arr1=array.copy()
arr1[2:]=10
print(array)
print(arr1)

[1 2 3 4 5]
[ 1  2 10 10 10]


In [30]:
arr1*2

array([ 2,  4, 20, 20, 20])

In [33]:
l1

[1, 2, 34, 5]

In [1]:
 
    marks=([30,40,20],[30,24,39],[23,44,23])
    

In [5]:
np.array(marks)

array([[30, 40, 20],
       [30, 24, 39],
       [23, 44, 23]])

In [8]:
np.arange(3,23)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [9]:
np.arange(5,45,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])