In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Saurabh\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | 3          |   3% 
conda-4.14.0         | 937 KB    | #5         |  15% 
conda-4.14.0         | 937 KB    | ###7       |  38% 

Note: you may need to restart the kernel to use updated packages.
conda-4.14.0         | 937 KB    | #####

In [4]:
import numpy as np

In [21]:
lst=[1,2,3,4,5]
array=np.array(lst)

In [4]:
type(array)

numpy.ndarray

In [22]:
array

array([1, 2, 3, 4, 5])

In [23]:
array.shape

(5,)

In [10]:
l1=[1,2,34,5]
l2=[4,8,6,7]
array=np.array([l1,l2])

In [11]:
array

array([[ 1,  2, 34,  5],
       [ 4,  8,  6,  7]])

In [14]:
array.reshape(4,2)

array([[ 1,  2],
       [34,  5],
       [ 4,  8],
       [ 6,  7]])

In [15]:
array.reshape(1,8)

array([[ 1,  2, 34,  5,  4,  8,  6,  7]])

In [18]:
array[1:,5:]

array([], shape=(1, 0), dtype=int32)

In [24]:
array

array([1, 2, 3, 4, 5])

In [26]:
array[4]

5

In [29]:
arr1=array.copy()
arr1[2:]=10
print(array)
print(arr1)

[1 2 3 4 5]
[ 1  2 10 10 10]


In [30]:
arr1*2

array([ 2,  4, 20, 20, 20])

In [33]:
l1

[1, 2, 34, 5]

In [1]:
 
    marks=([30,40,20],[30,24,39],[23,44,23])
    

In [5]:
np.array(marks)

array([[30, 40, 20],
       [30, 24, 39],
       [23, 44, 23]])

In [8]:
np.arange(3,23)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In [9]:
np.arange(5,45,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [14]:
np.ones((6,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.linspace(0,14,9)

array([ 0.  ,  1.75,  3.5 ,  5.25,  7.  ,  8.75, 10.5 , 12.25, 14.  ])

In [15]:
np.linspace(0,15,6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [16]:
np.linspace(3,15,4)

array([ 3.,  7., 11., 15.])

In [42]:
np.eye(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [43]:
np.random.rand(3,6)

array([[0.95804178, 0.45081465, 0.36083502, 0.78271994, 0.76654967,
        0.83642855],
       [0.58860509, 0.10485232, 0.14538797, 0.47985952, 0.33180708,
        0.55173094],
       [0.88844743, 0.05223873, 0.52437216, 0.28495834, 0.16446648,
        0.15334035]])

In [44]:
np.random.randn(3,6)

array([[-0.23855946,  1.46518048, -0.01073576, -1.76524427, -0.92461609,
        -0.70744894],
       [ 0.06906442,  0.62319602,  1.19958656,  0.16769751, -0.7773371 ,
        -0.37326802],
       [ 0.66377818, -0.39650537,  1.65356158, -0.51063751, -1.23511582,
         1.18862197]])

In [45]:
np.random.randint(0,12,15)

array([ 9,  7, 10,  3,  5, 11,  7,  0,  7,  5,  6,  6,  8,  1,  5])

In [46]:
np.random.randint(20,50,20)

array([32, 39, 31, 35, 49, 42, 20, 30, 38, 45, 33, 26, 38, 28, 20, 45, 44,
       28, 36, 48])

In [47]:
sample_array=np.arange(4,15)
sample_array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
rand_array=np.random.randint(0,15,3)
rand_array

array([ 7, 11,  5])

In [49]:
sample_array.min()
4

4

In [50]:
sample_array.argmin()
0

0

In [51]:
rand_array.max()

11

In [52]:
rand_array.argmax()

1

In [53]:
a=np.random.rand(3,5)
a

array([[0.42799595, 0.59689193, 0.77274166, 0.12829673, 0.04593363],
       [0.17092811, 0.21236209, 0.21279398, 0.63831226, 0.26440778],
       [0.20260276, 0.20737106, 0.93332987, 0.8584335 , 0.58426428]])

In [54]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix


array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [55]:
sample_matrix[1][2]

54

In [56]:
sample_matrix[2]

array([56, 76, 24,  7])

In [57]:
sample_array=np.arange(1,30)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [59]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12])

In [25]:
a=np.array([[1,2,3],[4,5,6]])
a
b=a.ndim
c=a.shape
d=a.size
b,c,d

(2, (2, 3), 6)

In [26]:
import pandas as pd


In [28]:
labels=['a','b','c','d']
list=[10,28,3,4]
import numpy as np
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}

In [29]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [30]:
pd.Series(data=list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [31]:
pd.Series(labels,list)

10    a
28    b
3     c
4     d
dtype: object

In [32]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [33]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [34]:
sports1['basketball']


3

In [35]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [37]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [38]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [39]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.056047  0.851555  0.807370  0.371989  0.751226
B  0.489954  0.830829  0.463749  0.484229  0.487633
C  0.114791  0.505677  0.881949  0.972004  0.129795
D  0.466027  0.191171  0.574981  0.287921  0.580886
E  0.579707  0.556644  0.463293  0.727837  0.444489
F  0.329049  0.686644  0.240551  0.263049  0.325016
G  0.472246  0.110371  0.007301  0.901981  0.025718
H  0.223764  0.896629  0.708871  0.719586  0.905588

In [40]:
df1[['score1','score2','score3']]

score1    score2    score3
A  0.056047  0.851555  0.807370
B  0.489954  0.830829  0.463749
C  0.114791  0.505677  0.881949
D  0.466027  0.191171  0.574981
E  0.579707  0.556644  0.463293
F  0.329049  0.686644  0.240551
G  0.472246  0.110371  0.007301
H  0.223764  0.896629  0.708871

In [41]:
x=np.random.rand(0,8)
y=np.random.rand(0,8)
z=np.random.rand(0,8)